### ISSUE TITLE
model内部文件报错

### ISSUE THREAD

**Issue by Nodewebzsz** [shenqihui/taro_scaffold#1]
`错误  编译失败  src/models/global.ts
{ SyntaxError: unknown: Unexpected token, expected ";" (127:18)

  125 |
  126 |
> 127 |             yield put({
      |                   ^
  128 |               type: 'SET_DATA',
  129 |               payload: {
  130 |                 windowWidth: res.windowWidth,
    at _class.raise (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:3893:15)
    at _class.unexpected (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:5222:16)
    at _class.semicolon (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:5206:40)
    at _class.parseExpressionStatement (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:7635:10)
    at _class.parseExpressionStatement (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:9914:69)
    at _class.parseStatementContent (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:7234:19)
    at _class.parseStatementContent (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:9850:58)
    at _class.parseStatement (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:7115:17)
    at _class.parseBlockOrModuleBlockBody (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:7666:23)
    at _class.parseBlockBody (/Users/zsz/Desktop/taro-wechat-demo/node_modules/@babel/parser/lib/index.js:7653:10)
  pos: 3076,
  loc: Position { line: 127, column: 18 },
  code: 'BABEL_PARSE_ERROR' }`

**Comment by shenqihui** [comment]
@Nodewebzsz  方不方便贴出整个该 effect 的代码？yield 的需要 `*function(){}` 类型的函数声明的.

**Comment by Nodewebzsz** [comment]
这个我刚才自己解决了

**Comment by Nodewebzsz** [comment]
刚刚碰到另外一个问题，我自己安装了dva-core的包，但是会报错，用你的本地文件就ok，你的文件做了其他处理么。报错如下：
`VM3234:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/core-js/library/fn/object/get-own-property-descriptor.js" is not defined 
 Error: module "npm/core-js/library/fn/object/get-own-property-descriptor.js" is not defined
    at require (http://127.0.0.1:44596/appservice/__dev__/WAService.js:22:20138)
    at http://127.0.0.1:44596/appservice/__dev__/WAService.js:22:19993
    at http://127.0.0.1:44596/appservice/npm/@babel/runtime/core-js/object/get-own-property-descriptor.js:1:328
    at require (http://127.0.0.1:44596/appservice/__dev__/WAService.js:22:20279)
    at http://127.0.0.1:44596/appservice/__dev__/WAService.js:22:19993
    at http://127.0.0.1:44596/appservice/npm/@babel/runtime/helpers/interopRequireWildcard.js:1:338`

引入包是这样的`import * as  dva from 'dva-core'`

**Comment by shenqihui** [comment]
#2 这里已经解答。Taro 中 node_modules 的不会编译及增加依赖。
